### ISSUE TITLE
Add conversion between particles as edges and particles as nodes

### ISSUE THREAD

**Issue by jacanchaplais** [jacanchaplais/graphicle#4]

**Comment by GiorgioCerro** [comment]
@jacanchaplais 
I made few progress and I'd like you to review them.
I added a new script (just as you suggested) where there is a new function that takes a graph and create the link graph, which switches edges and nodes. This is not a reversible process, therefore I suggest to include this as an option into the 'to_networkx' function. 

Also, there is an edge dictionary that would help to link the nodes with their attributes.

**Comment by jacanchaplais** [comment]
Thanks @GiorgioCerro, that's great! Being able to switch between these representations is so important, though, that I think it would be a good idea to have an internal state within the `Graphicle` object that determines whether it behaves as though the data is particles = edges, or particles = nodes. I can hash this out a bit to show you what I mean.

In general, the functions we write should only take this package's own objects as inputs and return them as outputs, as packaging the data externally as networkx objects couples us to that library forever.

I'll play with the function and see whether it is possible to get it reversible, so we can integrate it into the intrinsic behaviour of `Graphicle` objects.

Ideally we should have something like:
```python
>>> graph = Graphicle(...)
>>> graph.state
<State.EDGES: 'edges'>
>>> graph.adj.edges
# returns an array of edge pairs in same order as pdg, pmu, etc. data
>>> graph.state = 'nodes'
>>> graph.state
<State.NODES: 'nodes'>
>>> graph.adj.nodes
# returns an array of node indices in same order as pdg, pmu, etc. data
```

where I've renamed `graph.edges` -> `graph.adj`.

**Comment by jacanchaplais** [comment]
To clarify, both the edges and the nodes would be available at all times by doing `graph.adj.edges` or `graph.adj.nodes`, but the actual underlying connectivity would change depending on the state, edges would be in the same order as the `ParticleSet` for `<State.EDGES: 'edges'>`, whereas nodes would be in that order for `<State.NODES: 'nodes'>`.

**Comment by jacanchaplais** [comment]
@GiorgioCerro, your idea about using `networkx.line_graph`, and relabelling the nodes for external users got me thinking, and I had some ideas about how to implement. I have pushed a state based solution as described above, which should have the nodes relabelled and in the same order of the particle lists. Would you mind testing it out and seeing if it gives you the right structure? :)

**Comment by GiorgioCerro** [comment]
@jacanchaplais That's a great idea, being able to switch between nodes/edges states. I checked the code it seems to work. 
Here few comments:

- when switching states, I would change everything, without leaving any track of the other state. For examples, when you choose the node state, you still have all the edges in the other state when you call graphicle.edges, graphicle.edges.data
- still need to change to_networkx, cause if we are in the node states it'd be nicer to have the network in that state

**Comment by jacanchaplais** [comment]
Thanks, @GiorgioCerro! I have tried to address these issues slightly differently. I added a  `transform` module, and done away with the state interface. The state interface turned out to be too constricting, as it made the assumption that `Graphicle` objects necessarily represented the full particle shower.

The new solution works as follows:
```python
>>> from graphicle import transform
>>> # restructuring existing graph:
>>> graph.adj = transform.particle_as_node(graph.adj)
```

I have merged this into `release/0.1` (which I shouldn't have done this soon - oops); would you mind playing with it and seeing how you like it?

Also, I should note that I replaced the `to_networkx` method with `to_dicts`, which can be used to create NetworkX graphs, but is hopefully more flexible and won't couple us to NetworkX forever.
